### ISSUE TITLE
Define the Cloud Monitoring category for custom metrics

### ISSUE THREAD

**Issue by aaaaahaaaaa** [GoogleCloudPlatform/opentelemetry-operations-python#296]
Based on the example [here](https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/blob/main/docs/examples/cloud_monitoring/basic_metrics.py), the name of the counter (`request_counter`) ends up being both used for the name of the metric (`workload.googleapis.com/request_counter`) and the name of the `Active metric category` under Cloud Monitoring. The result is:

```
Generic Task > Request_counter > Request_counter
```

Is there a way a define the category in such a way that the results would:
```
Generic Task > My Category > Request_counter
```
And therefore group multiple custom metrics under the same category?

**Comment by aabmass** [comment]
Iirc, if the metric has the form `workload.googleapis.com/foo/bar`, the UI will render foo as the category. Can you try that?

**Comment by aaaaahaaaaa** [comment]
So the name of the metric would include the `/`? 

That doesn't work, OpenTelemetry raise the following exception:
```
Exception: Expected ASCII string of maximum length 63 characters but got foo/bar.
```

**Comment by aabmass** [comment]
That was fixed in https://github.com/open-telemetry/opentelemetry-python/pull/3442. Can you try a newer version of OpenTelemetry API/SDK?

**Comment by aabmass** [comment]
@aaaaahaaaaa is this still an issue for you?

**Comment by aaaaahaaaaa** [comment]
@aabmass Sorry for the late feedback, this one slipped through the cracks.

It works, the prefix before the `/` appears as the category. Thank you :)

For the record, the name of metric in the UI still appears as the full string with the prefix. So `category` -> `category/metric`.
